### ISSUE TITLE
Basic Log

### ISSUE THREAD

**Issue by raitono** [RyanFCarr/CannaLog#1]
The log will need to have some basic fields. If a previous log exists, autofill with those values.

Log Date (Autofilled but editable)

Plant Age (Autofilled based on transplant date)

Tag

Res change
Additive

Water
Hydroguard
Base Nutrients
Micro
Bloom
CalMag
Environmental Factors

Air Temp
Humidity
PH
Initial/Final
Additives
Any number of logs
Hydro
Temp
PPM
Start/After Nutes
Any number of logs
Plant Height

Light Height (Top of Plant)

Notes

**Comment by RyanFCarr** [comment]
The log will need to have some basic fields.

- Log Date (Autofilled)
- Plant Age (Autofilled)

- Additive
    - Water
    - Base Nutrients
        - Micro
        - Bloom
        - CalMag

- Environmental Factors
    - Air Temp 
    - Humidity
    - PH
        - Start/End
    - Hydro
        - Temp
        - PPM
            - Start/After Nutes

- Plant Height
- Light Height (Top of Plant)

- Notes
